package com.staples.eCatalogue.constants;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class ConvertorConstants {
	public static final String QUALIFIER_ROOT = "Qualifier root";
	public static final String STD_BU_ALL = "std.bu.all";
	public static final String STD_LANG_ALL = "std.lang.all";
	public static final String OK = "OK";
	public static final String NO_CONTENT = "NO_CONTENT";
	public static final String PACKAGING_INFORMATION = "PackagingInformation";
	public static final String PRODUCT_INFORMATION = "ProductInformation";	
	public static final String PRODUCT = "Product";
	public static final String ASSET = "Asset";
	public static final String QUALIFIER = "Qualifier";
	public static final String NAME_TAG = "Name";	
	public static final String USER_TYPE_ID = "UserTypeID";
	public static final String ID = "ID";
	public static final String SEMICOLAN = ";";
	public static final String PRODUCT_ID = "ProductID";
	public static final String ASSET_ID = "AssetID";
	public static final String STATUS = "Status";
	public static final String CLASSIFICATION_ID = "ClassificationID";
	public static final String CONFIGURATION_ID = "ConfigurationID";
	public static final String TYPE = "Type";
	public static final String PRODUCT_CROSS_REFERENCE = "ProductCrossReference";
	public static final String ASSET_CROSS_REFERENCE = "AssetCrossReference";
	public static final String CLASSIFICATION_REFERENCE = "ClassificationReference";
	public static final String CONTEXT = "Context";
	public static final String QUALIFIER_ID = "QualifierID";
	public static final String DERIVED_CONTEXT_ID = "DerivedContextID";
	public static final String MULTI_VALUE = "MultiValue";
	public static final String VALUE_GROUP = "ValueGroup";
	public static final String ATTRIBUTE_ID = "AttributeID";
	public static final String VALUE = "Value";
	public static final String TRUE = "true";
	public static final String FALSE = "false";
	public static final String PACKAGING_DOT = "Packaging.";
	public static final String PACKAGING_BASE_UNIT = "Packaging.BaseUnit";
	public static final String PACKAGING_ADDITIONAL_UNIT = "Packaging.AdditionalUnit";
	public static final String PRODUCT_LIFE_CYCLE_STATUS = "ProductLifeCycleStatus";
	public static final String DC_PRODUCT_LIFE_CYCLE_STATUS = "DistributionChainProductLifeCycleStatus";
	public static final String ARTICLE_EXISTS_IN_DC = "ArticleExistsInDistributionChain";
	public static final String DC_SALES_PACKAGING_LINE = "DistributionChainSalesPackagingLine";
	public static final String SITE_PRODUCT_LIFE_CYCLE_STATUS = "SiteProductLifeCycleStatus";
	public static final String SALES_PACKAGING_UNIT = "SalesPackagingUnit";
	public static final String PRODUCT_LIFE_CYCLE_STATUS_EO = "ProductLifeCycleStatusEasyOrder";
	public static final String WEB_PRODUCT_TITLE_ADVANTAGE = "WebProductTitleAdvantage";	
	public static final String TYPOLOGY_NAME = "TypologyName";
	public static final String TYPOLOGY = "Typology";
	public static final String COMMERCIAL_TEXT_ADVANTAGE = "CommercialTextAdvantage";
	public static final String PRODUCT_TITLE_ADVANTAGE = "ProductTitleAdvantage";
	public static final String PRODUCT_TITLE_PAPER_ADVANTAGE = "ProductTitlePaperAdvantage";
	public static final String PRODUCT_PRICE_GRID_FEATURE = "ProductPriceGridFeature";
	public static final String PRODUCT_SUBTITLE_ADVANTAGE = "ProductSubTitleAdvantage";
	public static final String PRODUCT_SUBTITLE_PAPER_ADVANTAGE = "ProductSubTitlePaperAdvantage";
	public static final String PRODUCT_TEXT_PAPER_ADVANTAGE = "ProductTextPaperAdvantage";
	public static final String LEN_CODE = "LENCode";
	public static final String ARTICLE_CODE = "ArticleCode";
	public static final String ACTIVE_FOR_COUNTRY = "ActiveForCountry";
	public static final String ACTIVE_FOR_LANGUAGE = "ActiveForLanguage";
	public static final String ASSET_PUSH_LOCATION_GENESIS_STANDARD = "AssetPushLocationGenesisStandard";
	public static final String ASSET_PUSH_LOCATION = "AssetPushLocation";
	public static final String GENESIS_STANDARD = "GenesisStandard";
	public static final String EASY_ORDER_STANDARD = "EasyOrderStandard";
	public static final String BREADCRUMB_NODES = "BreadcrumbNodes";
	public static final String REFERENCED_PACKAGINGS = "Referenced packagings";
	public static final String PACKAGING_IDS = "PackagingIDs";
	public static final String GTIN = "GTIN";
	public static final String MAIN_GTIN = "MainGTIN";
	public static final String EXTERNAL_CLASSIFICATIONS = "ExternalClassifications";
	public static final String HAZARDOUS_MATERIAL = "HazardousMaterial";
	public static final String ARTICLE_TYPE = "ArticleType";
	public static final String KEYWORDS_PAPER = "KeywordsPaper";
	public static final String PAPER_BANNER_TEXT = "PaperBannerText";
	public static final String PAPER_VISUAL_CATCH_LINE_EXPORT = "PaperVisualCatchLineExport";
	public static final String PAPER_PROMOTIONAL_TEXT = "PaperPromotionalText";
	public static final String KEY_SELLING_POINTS_PAPER = "KeySellingPointsPaper";
	public static final String PRODUCT_TEXT_PAPER_ONLINE = "ProductTextPaperOnline";
	public static final String CATCH_LINE_PAPER = "CatchLinePaper";
	public static final String PRODUCT_SUB_TITLE_PAPER_ONLINE = "ProductSubTitlePaperOnline";
	public static final String PRODUCT_TITLE_PAPER_ONLINE = "ProductTitlePaperOnline";
	public static final String INSTALLATION_FEE = "InstallationFee";
	public static final String INSTALLABLE = "Installable";
	public static final String ENABLE_INLINE_CONTENT = "EnableInlineContent";
	public static final String ENABLE_EXPERT_REVIEWS = "EnableExpertReviews";
	public static final String LINKS_TO_EXTERNAL_VIDEOS = "LinksToExternalVideos";
	public static final String PRODUCT_REFERENCE_COORDINATED_ITEMS = "ProductReferenceCoordinatedItems";
	public static final String COORDINATED_ITEMS = "CoordinatedItems";
	public static final String ECO_EASY_TAG = "Staples.S03985";
	public static final String ECO_EASY = "EcoEasy";
	public static final String ICONS = "Icons";
	public static final String ICON = "Icon";
	public static final String DOCUMENTS = "Documents";
	public static final String SECONDARY_IMAGES = "SecondaryImages";
	public static final String SECONDARY_IMAGE = "Secondary Image";
	public static final String PRIMARY_IMAGE_PAPER_CENTRAL = "PrimaryImagePaperCentral";
	public static final String PRIMARY_IMAGE_PAPER_LOCAL = "PrimaryImagePaperLocal";
	public static final String PRIMARY_IMAGE_PAPER = "PrimaryImagePaper";
	public static final String PRIMARY_IMAGE_CENTRAL = "PrimaryImageCentral";
	public static final String PRIMARY_IMAGE_LOCAL = "PrimaryImageLocal";
	public static final String PRIMARY_IMAGE = "PrimaryImage";
	public static final String PRIMARY_IMAGE_SPACE = "Primary Image";
	public static final String PRIMARY_IMAGE_EASY_ORDER = "PrimaryImageEasyOrder";
	public static final String KEYWORDS = "Keywords";
	public static final String BRAND_PROMISE_LINE = "BrandPromiseLine";
	public static final String LINKS_TO_EXTERNAL_CONTENT = "LinksToExternalContent";
	public static final String LINKS_TO_ADDITIONAL_DOCUMENTATION = "LinksToAdditionalDocumentation";
	public static final String EXTENDED_SELLING_POINTS = "ExtendedSellingPoints";
	public static final String KEY_SELLING_POINTS = "KeySellingPoints";
	public static final String COMMERCIAL_TEXT = "CommercialText";
	public static final String CATCH_LINE = "CatchLine";
	public static final String WEB_PRODUCT_TEXT = "WebProductText";
	public static final String WEB_PRODUCT_TEXT_ADVANTAGE = "WebProductTextAdvantage";
	public static final String PRODUCT_TITLE = "ProductTitle";
	public static final String ARTICLE_STANDARD_ERP_DESCRIPTION = "ArticleStandardERPDescription";
	public static final String DESCRIPTION = "Description";
	public static final String BREADCRUMB_WEB_HIERARCHY_CLASSIFICATION_REFERENCES = "BreadcrumbWebHierarchyClassificationReferences";
	public static final String WEB_HIERARCHY_CLASSIFICATION_REFERENCES = "WebHierarchyClassificationReferences";
	public static final String WEB_HIERARCHY = "WebHierarchy";
	public static final String ONLINE = "Online";
	public static final String BRAND_LOGOS = "BrandLogos";
	public static final String BRAND_LOGO = "BrandLogo";
	public static final String PUBLICATION_BRAND = "PublicationBrand";
	public static final String BRAND_CALCULATED = "BrandCalculated";
	public static final String ASSORTMENT_TYPE = "AssortmentType";
	public static final String PRODUCT_PRIORITY = "ProductPriority";
	public static final String PRODUCT_TO_BE_PUBLISHED = "ProductToBePublished";
	public static final String TAX_CODE = "TaxCode";
	public static final String STAPLESEUR = "STAPLESEUR";
	public static final String MANUFACTURER_PART_NUMBER = "ManufacturerPartNumber";
	public static final String SPGS_CODE_CALCULATED = "SPGSCodeCalculated";
	public static final String PRODUCT_TYPE = "ProductType";
	public static final String PARENT_ID = "ParentID";
	public static final String NAME = "Name";
	public static final String ACTIVE_ASSORTMENT = "Active assortment";
	public static final String ADVANTAGE_WEB_HIERARCHY_ID = "AdvantageWebHierarchyID";
	public static final String ADVANTAGE_BREAD_CRUMB_WEB_HIERARCHY_ID = "AdvantageBreadCrumbWebHierarchyID";
	public static final String EASY_ORDER_CODE_CALCULATED = "EasyOrderCodeCalculated";
	public static final String ACCESSORY_PRODUCTS = "AccessoryProducts";
	public static final String ACCESSORY_PRODUCT = "AccessoryProduct";
	public static final String ALTERNATIVE_PRODUCTS = "AlternativeProducts";
	public static final String ALTERNATIVE_PRODUCT = "AlternativeProduct";
	
	public static final String BREADCRUMBS = "Breadcrumbs";
	public static final String BREADCRUMB = "Breadcrumb";
	public static final String RELATED_ITEMS = "Related items";
	public static final String ALTERNATIVES = "Alternatives";
	public static final String BULLET_POINTS = "Bullet points";
	public static final String PRODUCT_DESCRIPTION = "Product description";
	public static final String ICON_IMAGES = "Icon images";
	public static final String BRAND_IMAGES = "Brand images";
	public static final String PRODUCT_IMAGE = "Product image";
	public static final String IMAGE_COMING_SOON = "Image coming soon";
	public static final String WEB_TITLE = "Web title";
	public static final String NOT_PUBLISHED = "Not published";
	public static final String DUPLICATE_PACKAGINGS = "Duplicate packagings";
	public static final String TRUNCATED_LOCAL_CODES = "TruncatedLocalCodes";
	public static final String WEB_PRODUCT_TITLE_ADVANTAGE_LEGACY = "WebProductTitleAdvantageLegacy";
	public static final String WEB_PRODUCT_TITLE_ONLINE_LEGACY = "WebProductTitleOnlineLegacy";
	public static final String PROMOTIONAL_PRODUCT_PACKAGING_LINE = "PromotionalProductPackagingLine";
	public static final String PACKAGING_LINE_LEGACY = "PackagingLineLegacy";
	public static final String WEB_ID_EXPORT = "WebIDExport";
	public static final String WEB_ID = "WebID";
	public static final String CONVERSION_FACTOR_TO_BASE_UNIT = "ConversionFactorToBaseUnit";
	public static final String CONTENT_UOM_LEGACY = "ContentUOMLegacy";
	public static final String CONTENT_QUANTITY_LEGACY = "ContentQuantityLegacy";
	public static final String DISPLAY_UNIT_OF_MEASURE = "DisplayUnitOfMeasure";
	public static final String SALES_UOM_LEGACY = "SalesUOMLegacy";
	public static final String EU_CODE = "EUCode";
	public static final String PACKAGING_ID = "PackagingID";
	public static final String LOCAL_CODE = "LocalCode";
	public static final String MARKING = "X";
	public static final String PROCESSING_BACKLOGS = "Processing backlogs";
	public static final String REQUESTED_URL_NOT_FOUND = "Requested URL not found";
	public static final String MISSING_CONTENT = "Missing content";
	public static final String MISSING_MANDATORY_INFORMATION = "Missing mandatory information";
	public static final String DATA_INTEGRITY_VIOLATIONS = "Data integrity violations";
	public static final String DATA_QUALITY_ASSESSMENT = "Data Quality Assessment";
	public static final String ERP_STATUS = "ERP status";
	public static final String ADVANTAGE = "Advantage";
	public static final String SEPARATOR = ";";
	public static final String COMMA = ",";
	public static final String EO = "EO,";
	public static final String SEOFR = "SEOFR";
	public static final String YES = "Yes";
	public static final String FONT_NAME = "Calibri";
	public static final String MISSING_LOCAL_CODES_FILE_NAME = "-missingLocalCodesInStep";
	public static final String MULTIPLE_REF_LOCAL_CODES_FILE_NAME = "-multipleTimesReferencedLocalCodesInStep";
	public static final String ADVANTAGE_CHANNEL = "AdvantageChannel";
	
	public static final String XLSX = ".xlsx";
	public static final String XML = ".xml";
	public static final String WEEKLY_ARTICLE_REPORT = "WeeklyArticleReport-";
	public static final String ZIP = ".zip";
	public static final String TXT = ".txt";
	public static final String ACTIVE_ASSORTMENTS = "ActiveAssortments";
	public static final String UNZIP = "Unzip";
	public static final String ARCHIVE = "Archive";
	public static final String INVALID_DATA_QUALITY_ASSESSMENT_FLAGS = "Invalid data quality assessment flags - job aborted";
	public static final String DOES_NOT_EXIST = "' does not exist";
	public static final String DESTINATION_FOLDER = "[destination folder] '";
	public static final String USAGE_COMMAND = "Usage: java -jar [jar name] [source folder] [destination folder] [data quality assessment flags]";
	public static final String SOURCE_FOLDER = "[source folder] '";
	public static final String INVALID_ARGUMENTS_JOB_ABORTED = "Invalid arguments - job aborted";
	public static final String STATUS_ON_EASYORDER = "Status on EasyOrder";
	public static final String LOG_FILE_NAME = "StepArticleReports-";
	public static final String VALID_DATA_QUALITY_ASSESSMENT_FLAGS_SET1 = "Valid data quality assessment flags: [PRD] [PRD,EO,] [PRD,EO,ActiveAssortment] [PRD,EO,ActiveAssortment,RestrictedToActiveAssortment] [PRD,RestrictedToActiveAssortment]";
	public static final String VALID_DATA_QUALITY_ASSESSMENT_FLAGS_SET2 = "                                     [QA]  [QA,EO,]  [QA,EO,ActiveAssortment]  [QA,EO,ActiveAssortment,RestrictedToActiveAssortment]  [QA,RestrictedToActiveAssortment]";
	public static final String LOG = "Log";
	public static final String LOG4J_LOG_NAME = "/log/WeeklyReportLog.log";
	public static final String ARTICLE_EXISTS_IN_SITE = "ArticleExistsInSite";
	public static final String DELIVERING_SITE = "DeliveringSite";
	
	//List of fast BUs
	public static final List<String> FAST_BU_LIST = new ArrayList<String>(){{
		add("96725-en");
		add("96725-fr");
		add("96725-de");
		add("96741-en");
		add("96741-fr");
		add("96741-de");
		//add("xx-all");
	}};
	
	
	// Holds the width for each column
	public static final HashMap<String, Integer> packageColumnsWidth = new HashMap<String, Integer>(){{		
		put(ConvertorConstants.LOCAL_CODE, 4300);
		put(ConvertorConstants.LEN_CODE, 2900);
		put(ConvertorConstants.ARTICLE_CODE, 3600);
		put(ConvertorConstants.PRODUCT_ID, 3400);
		put(ConvertorConstants.PACKAGING_ID, 4300);
		put(ConvertorConstants.EU_CODE, 3300);
		put(ConvertorConstants.PRODUCT_LIFE_CYCLE_STATUS, 6900);
		put(ConvertorConstants.SALES_UOM_LEGACY	, 5700);
		put(ConvertorConstants.DISPLAY_UNIT_OF_MEASURE, 5900);
		put(ConvertorConstants.CONTENT_QUANTITY_LEGACY, 6800);
		put(ConvertorConstants.CONTENT_UOM_LEGACY, 5700);
		put(ConvertorConstants.CONVERSION_FACTOR_TO_BASE_UNIT, 7700);
		put(ConvertorConstants.WEB_ID, 4300);
		put(ConvertorConstants.WEB_ID_EXPORT, 4300);
		put(ConvertorConstants.PACKAGING_LINE_LEGACY, 6800);
		put(ConvertorConstants.PROMOTIONAL_PRODUCT_PACKAGING_LINE, 9000);
		put(ConvertorConstants.WEB_PRODUCT_TITLE_ONLINE_LEGACY, 25000);
		put(ConvertorConstants.WEB_PRODUCT_TITLE_ADVANTAGE_LEGACY, 25000);
		put(ConvertorConstants.MAIN_GTIN, 5300);
		put(ConvertorConstants.GTIN, 5300);
		put(ConvertorConstants.TRUNCATED_LOCAL_CODES, 7700);
		put(ConvertorConstants.PRODUCT_LIFE_CYCLE_STATUS, 6800);
		put(ConvertorConstants.DUPLICATE_PACKAGINGS, 6400);
		put(ConvertorConstants.PACKAGING_LINE_LEGACY, 6100);
		put(ConvertorConstants.WEB_PRODUCT_TITLE_ONLINE_LEGACY, 8700);
		put(ConvertorConstants.WEB_PRODUCT_TITLE_ADVANTAGE_LEGACY, 8900);
		put(ConvertorConstants.ACTIVE_ASSORTMENT, 6500);
		put(ConvertorConstants.NOT_PUBLISHED, 5000);
		put(ConvertorConstants.WEB_TITLE, 4100);
		put(ConvertorConstants.IMAGE_COMING_SOON, 6500);
		put(ConvertorConstants.PRODUCT_IMAGE, 5000);
		put(ConvertorConstants.BRAND_IMAGES, 4900);
		put(ConvertorConstants.ICON_IMAGES, 4700);
		put(ConvertorConstants.PRODUCT_DESCRIPTION, 6400);
		put(ConvertorConstants.BULLET_POINTS, 4600);
		put(ConvertorConstants.ALTERNATIVES, 4600);
		put(ConvertorConstants.RELATED_ITEMS, 4900);
		put(ConvertorConstants.DOCUMENTS, 4400);
		put(ConvertorConstants.BREADCRUMBS, 4700);
	}};
	
	// Holds the width for each column
	public static final HashMap<String, Integer> productColumnsWidth = new HashMap<String, Integer>(){{
		put("ArticleCode", 3600);
		put("ProductID", 3400);
		put("LENCode", 2900);
		put("Name", 25000);
		put("ParentID", 4300);
		put("TypologyName", 7700);
		put("ProductType", 7700);
		put("SPGSCodeCalculated", 6000);
		put("ManufacturerPartNumber", 6800);
		put("TaxCode ", 3800);
		put("ProductLifeCycleStatus", 6900);
		put("ActiveForCountry", 9000);
		put("ActiveForLanguage", 9000);
		put("ProductToBePublished", 6100);
		put("ProductPriority", 5000);
		put("AssortmentType", 5100);
		put("BrandCalculated", 9000);
		put("PublicationBrand", 5100);
		put("BrandLogos", 5100);
		put("WebHierarchyClassificationReferences", 22000);
		put("BreadcrumbWebHierarchyClassificationReferences", 19000);
		put("Description", 16000);
		put("ArticleStandardERPDescription", 13000);
		put("ProductTitle", 19000);
		put("WebProductText", 20000);
		put("WebProductTextAdvantage",20000);
		put("CatchLine", 19000);
		put("CommercialText", 20000);
		put("KeySellingPoints", 15000);
		put("ExtendedSellingPoints", 10000);
		put("LinksToAdditionalDocumentation", 10000);
		put("LinksToExternalContent", 10000);
		put("BrandPromiseLine", 19000);
		put("Keywords", 10000);
		put("PrimaryImageEasyOrder", 6500);
		put("PrimaryImage", 6500);
		put("PrimaryImageLocal", 6500);
		put("PrimaryImageCentral", 6600);
		put("PrimaryImagePaper", 6500);
		put("PrimaryImagePaperLocal", 7500);
		put("PrimaryImagePaperCentral", 8500);
		put("SecondaryImages", 20000);
		put("Documents", 20000);
		put("Icons", 10000);
		put("EcoEasy", 3000);
		put("CoordinatedItems", 22000);
		put("ProductReferenceCoordinatedItems", 22000);
		put("LinksToExternalVideos", 10000);
		put("EnableExpertReviews", 6000);
		put("EnableInlineContent", 6000);
		put("Installable", 3500);
		put("InstallationFee", 5000);
		put("ProductTitlePaperOnline", 19000);
		put("ProductSubTitlePaperOnline", 19000);
		put("CatchLinePaper", 19000);
		put("ProductTextPaperOnline", 20000);
		put("KeySellingPointsPaper", 15000);
		put("PaperPromotionalText", 15000);
		put("PaperVisualCatchLineExport", 15000);
		put("PaperBannerText", 15000);
		put("KeywordsPaper", 15000);
		put("ArticleType", 5500);
		put("HazardousMaterial", 5500);
		put("ExternalClassifications", 20000);
		put("MainGTIN", 5000);
		put("GTIN", 12000);
		put("PackagingIDs", 12000);
		put("Referenced packagings", 6650);
		put("BreadcrumbNodes", 5500);
		put("LinksToExternalVideos", 6100);
		put("ProductLifeCycleStatus", 6650);
		put("ActiveForCountry", 5450);
		put("AssortmentType", 5000);
		put("ArticleType", 4000);
		put("PublicationBrand", 5000);
		put("SPGSCodeCalculated", 6000);
		put("TaxCode", 3500);
		put("WebHierarchyClassificationReferences", 9750);
		put("ProductTitle", 4800);
		put("WebProductText", 5500);
		put("Keywords", 3500);
		put("PrimaryImage", 4500);
		put("AssetPushLocationGenesisStandard", 9500);
		put("Active assortment", 6500);
		
		put("WebHierarchyClassificationReferences", 15000);
		put("AdvantageWebHierarchyID", 15000);
		put("AdvantageBreadCrumbWebHierarchyID", 10000);
		put("EasyOrderCodeCalculated", 7500);
		put("Description", 16000);
		put("ArticleStandardERPDescription", 13000);
		put("ProductTitle", 19000);
		put("ProductTitleAdvantage", 19000);
		put("ProductTitlePaperAdvantage", 19000);
		put("ProductPriceGridFeature", 19000);
		put("CatchLine", 19000);
		put("CommercialText", 20000);
		put("CommercialTextAdvantage", 20000);
		put("EnableInlineContent", 6000);
		put("KeySellingPoints", 15000);
		put("Keywords", 10000);
		put("PrimaryImageEasyOrder", 6500);
		put("PrimaryImage", 6500);
		put("PrimaryImageLocal", 6500);
		put("PrimaryImageCentral", 6600);
		put("PrimaryImagePaper", 6500);
		put("PrimaryImagePaperLocal", 7500);
		put("PrimaryImagePaperCentral", 8500);
		put("SecondaryImages", 20000);
		put("Documents", 20000);
		put("Icons", 10000);
		put("EcoEasy", 3000);
		put("AccessoryProducts", 15000);
		put("AlternativeProducts", 15000);
		put("ProductSubTitleAdvantage", 19000);
		put("ProductSubTitlePaperAdvantage", 19000);
		put("ProductTextPaperAdvantage", 20000);
		put("ArticleType", 5200);
		put("HazardousMaterial", 5500);
		put("ExternalClassifications", 10000);
		put("MainGTIN", 5000);
		put("GTIN", 12000);
		put("PackagingIDs", 12000);
		put("Referenced packagings", 6650);
		put("ProductLifeCycleStatus", 6650);
		put("ActiveForCountry", 5450);
		put("AssortmentType", 5000);
		put("ArticleType", 4000);
		put("PublicationBrand", 5000);
		put("SPGSCodeCalculated", 6000);
		put("WebHierarchyClassificationReferences", 9700);
		put("ProductTitleAdvantage", 6500);
		put("CommercialTextAdvantage", 8100);
		put("Keywords", 3500);
		put("PrimaryImage", 4500);
		put("AssetPushLocationEasyOrderStandard", 9600);
		put("PrimaryImageEasyOrder", 7500);
		put("Active assortment", 6200);
	}};
	
	// Holds the width for each column
	public static final HashMap<String, Integer> productCalculatedColumnsWidth = new HashMap<String, Integer>(){{
		put("Referenced packagings", 5700);
		put("BreadcrumbNodes", 5700);
		put("LinksToExternalVideos", 5700);
		put("ProductLifeCycleStatus", 5700);
		put("ActiveForCountry", 5700);
		put("AssortmentType", 5700);
		put("ArticleType", 5700);
		put("SPGSCodeCalculated", 5700);
		put("PublicationBrand", 5700);
		put("TaxCode", 5700);
		put("WebHierarchyClassificationReferences", 9700);
		put("ProductTitle", 5700);
		put("WebProductText", 5700);
		put("Keywords", 5700);
		put("PrimaryImage", 5700);
		put("AssetPushLocationGenesisStandard", 9500);
		put("Active assortment", 5700);		
	}};
	
	
}
